version: '3.1'
services:
  db:
    container_name: ${PROJECT}-mysql
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${PWD}/data/mysql:/var/lib/mysql
      - ${PWD}:/var/www
    ports:
      - ${MYSQL_PORT}:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - bridge

  php-fpm:
    container_name: ${PROJECT}-php-fpm
    build: .docker/php-fpm/
    restart: always
    ports:
      - ${FPM_PORT}:1010
    environment:
      - APPLICATION_ENV=${APPLICATION_ENV}
    volumes:
      - ${PWD}:/var/www
    working_dir: /var/www
    networks:
      - bridge

  nginx:
    container_name: ${PROJECT}-nginx
    build: .docker/nginx/
    restart: always
    depends_on:
      - php-fpm
    environment:
      - APPLICATION_ENV=${APPLICATION_ENV}
      - ${PROJECT}
      - ${SITE_NAME}
      - ${FPM_HOST}
      - ${FPM_PORT}
    volumes:
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}:/var/www
    ports:
      - ${NGINX_PORT}:80
    networks:
      - bridge

  beanstalkd:
    image: placeloop/beanstalkd
    container_name: ${PROJECT}-beanstalkd
    ports:
      - 11300:11300
    volumes:
      - ./data/beanstalkd:/binlog

networks:
  bridge:
    driver: bridge
